### ISSUE TITLE
Add Support for Davical other readable calendars

### ISSUE THREAD

**Issue by Reigns95** [adobo/agendav#193] opened 2016-12-06 15:12 UTC
I have the Problem that i can't see other readable calendars with a Davical Calendarserver. 
I*ve tested with Owncloud Calendarserver and there it works.
Please make it work for Davical"!

**Comment by adobo** [comment] 2016-12-07 18:45
Could you elaborate, please? Is this related to #43?

**Comment by Reigns95** [comment] 2016-12-08 08:17
Yes it is. Sry I didn't see that :/

**Comment by adobo** [comment] 2016-12-08 11:01
Don't worry! I'm closing this one as duplicate of #43

**Closed by adobo** 2016-12-08 11:01 UTC
